# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.ImageField(upload_to='pic_folder/')),
                ('ans1', models.ImageField(upload_to='pic_folder/')),
                ('ans2', models.ImageField(upload_to='pic_folder/')),
                ('ans3', models.ImageField(upload_to='pic_folder/')),
                ('ans4', models.ImageField(upload_to='pic_folder/')),
                ('ans5', models.ImageField(upload_to='pic_folder/')),
            ],
        ),
    ]
