# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameapp', '0002_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activeusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=0)),
                ('timetill', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapp.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
