# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_activeusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeusers',
            old_name='qid',
            new_name='qid1',
        ),
    ]
