# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_auto_20170903_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeusers',
            name='qid1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qid1', to='gameapp.Questions'),
        ),
    ]
