# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0005_auto_20170903_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeusers',
            name='qid2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qid2', to='gameapp.Questions'),
        ),
    ]
