# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0007_auto_20170903_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeusers',
            name='answer1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activeusers',
            name='answer2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activeusers',
            name='answer3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activeusers',
            name='answer4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activeusers',
            name='answer5',
            field=models.IntegerField(default=0),
        ),
    ]
