# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_auto_20170903_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeusers',
            name='isfinished',
            field=models.IntegerField(default=0),
        ),
    ]
