# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0009_activeusers_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeusers',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
