# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0010_activeusers_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkfun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id1', to='gameapp.Activeusers')),
                ('id2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id2', to='gameapp.Activeusers')),
            ],
        ),
    ]
