# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0011_checkfun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkfun',
            name='id1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkfun',
            name='id2',
            field=models.IntegerField(default=0),
        ),
    ]
