# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0013_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='ran',
            field=models.IntegerField(default=0),
        ),
    ]
